DC\CRMBundle\Entity\Company:
    type: mappedSuperclass
    fields:
        phone_office:
            type: string
            length: 255
        website:
            type: string
            length: 255
        description:
            type: string
            length: 255
        industry:
            type: string
            length: 255
        email_address:
            type: string
            length: 255