DC\CRMBundle\Entity\Person:
    type: mappedSuperclass
    fields:
        first_name:
            type: string
            length: 255
        last_name:
            type: string
            length: 255