imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    translator: { fallback: en }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    bundle: DCCRMBundle
    use_controller: true
    filters:
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules, /usr/local/lib/node]
            apply_to: "\.less$"
        cssrewrite: ~
    assets:
        fontawesome_css:
          inputs:
            - %kernel.root_dir%/../vendor/fontawesome/fontawesome/less/font-awesome.less
          filters:
            - less
            - cssrewrite
          output: css/fontawesome.css
        fontawesome_IE7_css:
          inputs:
            - %kernel.root_dir%/../vendor/fontawesome/fontawesome/less/font-awesome-ie7.less
          filters:
            - less
            - cssrewrite
          output: css/fontawesome_IE7.css

braincrafted_bootstrap:
    output_dir:
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js
    less_filter: less # "less", "lessphp" or "none"
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig


#swiftmailer:
#    delivery_address: me@example.com

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        # auto_mapping: true
        entity_managers:
            default:
                mappings:
                    DCCRMBundle: ~
services:
    metadata_manager:
        class: DC\CRMBundle\Services\Metadata\MetadataManager
    modules_helper:
        class: DC\CRMBundle\Services\Modules\ModulesHelper
    vardef_manager:
        class: DC\CRMBundle\Services\Vardef\VardefManager
genemu_form:
    autocomplete: ~