login:
    path:   /login
    defaults:  { _controller: DCCRMBundle:Security:login }
login_check:
    path:   /login_check
logout:
    path: /logout
_default:
    pattern:  /
    defaults: { _controller: DCCRMBundle:Default:index }
_list:
    pattern:  /{module}
    defaults: { _controller: DCCRMBundle:Default:list}
_new:
    pattern:  /{module}/new
    defaults: { _controller: DCCRMBundle:Default:new}
_edit:
    pattern:  /{module}/edit/{id}
    defaults: { _controller: DCCRMBundle:Default:edit}
_create:
    pattern:  /{module}/create
    defaults: { _controller: DCCRMBundle:Default:create}
_show:
    pattern:  /{module}/show/{id}
    defaults: { _controller: DCCRMBundle:Default:show }
_update:
    pattern:  /{module}/update/{id}
    defaults: { _controller: "DCCRMBundle:Default:update" }
    requirements: { _method: post|put }
_delete:
    pattern:  /{module}/delete/{id}
    defaults: { _controller: "DCCRMBundle:Default:delete" }
    requirements: { _method: post|delete }
_ajaxget:
    pattern: /getentitiesajax/{module}
    defaults: { _controller: "DCCRMBundle:Default:getEntitiesAjax" }


DCCRMBundle_account:
        resource: "@DCCRMBundle/Resources/config/routing/account.yml"
        prefix:   /
DCCRMBundle_contact:
        resource: "@DCCRMBundle/Resources/config/routing/contact.yml"
        prefix:   /